runtime: python310
entrypoint: gunicorn -b :$PORT app.server:app

runtime_config:
  operating_system: "ubuntu22"

env_variables:
  BUCKET: "977058370535_us_central1_import_csv"
  LOCATION: "us-central1"
  PROJECT: "qwiklabs-asl-00-d40c122a03de"
  service_account: "appengine-svc@qwiklabs-asl-00-d40c122a03de.iam.gserviceaccount.com"